"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!7f61pk+)5_s-e)&w(yi=c*t+bogd6tz!s$d_&is32gmg-3@dj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library.apps.LibraryConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_python.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],  # Không cần nếu template của app nằm đúng vị trí
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,  # BẮT BUỘC ĐỂ DJANGO TỰ TÌM template bên trong app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_python.context_processors.add_timestamp',
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "Education Library Admin",
    "site_header": "Education Library",
    "site_brand": "Education Library",
    "welcome_sign": "Chào mừng đến trang quản trị Education Library",
    "copyright": "",
    "hide_apps": ["auth"],

    

    # MENU BÊN TRÁI TÙY CHỈNH ĐÚNG CÚ PHÁP
    "side_menu_items": [
        
        {
            "app": "library",
            "label": "Quản lý thư viện",
            "models": [
                {"model": "library.Book", "name": "Sách"},
                {"model": "library.Author", "name": "Tác giả"},
                {"model": "library.Category", "name": "Danh mục"},
                {"model": "library.Publisher", "name": "Nhà xuất bản"},
                {"model": "library.Borrow", "name": "Mượn trả"},
                {"model": "library.Account", "name": "Tài khoản người dùng"},
            ]
        }
    ],

    "navigation_expanded": True,
}

WSGI_APPLICATION = 'django_python.wsgi.application'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "library" / "static",
]

CACHES = {
  "default": {
    "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
    "LOCATION": BASE_DIR / "django_cache",
    "TIMEOUT": None,
  }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
X_FRAME_OPTIONS = 'ALLOWALL'

# Cấu hình gửi mail qua SMTP của Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Khai báo thư viện xử lý email của Django
EMAIL_HOST = 'smtp.gmail.com' # Địa chỉ máy chủ SMTP của Google
EMAIL_PORT = 587 # Cổng gửi mail tiêu chuẩn của Gmail (TLS)
EMAIL_USE_TLS = True # Cho phép mã hóa dữ liệu khi gửi để đảm bảo bảo mật
EMAIL_HOST_USER = 'dangqpham0403@gmail.com' # Địa chỉ Gmail bạn dùng để gửi thông báo
EMAIL_HOST_PASSWORD = 'wcfs gzsx mszg sptz' # MẬT KHẨU ỨNG DỤNG (16 ký tự), không phải mật khẩu cá nhân
DEFAULT_FROM_EMAIL = 'Thư viện Education <dangqpham0403@gmail.com>' # Tên và mail hiển thị ở hộp thư người nhận

