"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file explicitly from BASE_DIR to ensure it works
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!7f61pk+)5_s-e)&w(yi=c*t+bogd6tz!s$d_&is32gmg-3@dj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library.apps.LibraryConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_python.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_python.context_processors.add_timestamp',
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "Education Library Admin",
    "site_header": "Education Library",
    "site_brand": "Education Library",
    "welcome_sign": "Chào mừng đến trang quản trị Education Library",
    "copyright": "",
    "hide_apps": ["auth"],
    "side_menu_items": [
        {
            "app": "library",
            "label": "Quản lý thư viện",
            "models": [
                {"model": "library.Book", "name": "Sách"},
                {"model": "library.Author", "name": "Tác giả"},
                {"model": "library.Category", "name": "Danh mục"},
                {"model": "library.Publisher", "name": "Nhà xuất bản"},
                {"model": "library.Borrow", "name": "Mượn trả"},
                {"model": "library.Account", "name": "Tài khoản người dùng"},
            ]
        }
    ],
    "navigation_expanded": True,
}

WSGI_APPLICATION = 'django_python.wsgi.application'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "library" / "static",
]

CACHES = {
  "default": {
    "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
    "LOCATION": BASE_DIR / "django_cache",
    "TIMEOUT": None,
  }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
X_FRAME_OPTIONS = 'ALLOWALL'

# Cấu hình gửi mail qua SMTP của Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_DESTINATION = os.getenv('EMAIL_DESTINATION', '')

# Xử lý trường hợp biến môi trường chưa load được để tránh lỗi NoneType
if EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = f"Thư viện Education <{EMAIL_HOST_USER}>"
else:
    DEFAULT_FROM_EMAIL = "Thư viện Education <noreply@library.com>"